artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/vikrant094/data_dir/raw/refs/heads/main/character_level_classification.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["Arabic.txt", "Chinese.txt","Czech.txt","Dutch.txt","English.txt","French.txt", "German.txt","Greek.txt","Irish.txt","Italian.txt","Japanese.txt","Korean.txt","Polish.txt","Portuguese.txt","Russian.txt","Scottish.txt","Spanish.txt","Vietnamese.txt"]

data_transformation:
  root_dir: artifacts/data_transformation
  STATUS_FILE: artifacts/data_transformation/status.txt

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_ckpt: artifacts/model_trainer/char_level_classfication_2.pth

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_ingestion/data
  model_path: artifacts/model_trainer/char_level_classfication_2.pth
  metric_file_name: artifacts/model_evaluation/metrics.csv